services:
  - type: web
    name: multimodal-content-generator
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: GROQ_API_KEY
        sync: false
      - key: HUGGING_FACE_API_KEY
        sync: false
    healthCheckPath: /api/health
